stages:
  - build
  - deploy
  - post-deploy

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  VERSION: $CI_COMMIT_SHA

build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_IMAGE --build-arg commitSha=$CI_COMMIT_SHA .
    - docker push $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
    
sentry/release:
  stage: build
  image: getsentry/sentry-cli
  script:
    - sentry-cli releases new -p web $VERSION
    - sentry-cli releases set-commits $VERSION --auto
  only:
    - master  

kube/deploy:
  stage: deploy
  image:
    name: lachlanevenson/k8s-kubectl
    # See https://gitlab.com/gitlab-org/gitlab-runner/issues/1421#note_61174777
    entrypoint: ['/bin/sh', '-c']
  variables:
    GIT_STRATEGY: none
  before_script:
    - kubectl config set-cluster default --server $KUBE_URL --insecure-skip-tls-verify
    - kubectl config set-credentials default --token $KUBE_TOKEN
    - kubectl config set-context default --cluster default --user default
    - kubectl config use-context default
  script:
    - kubectl set image deployments/web web=$CONTAINER_IMAGE
    - kubectl rollout status deployments/web --watch --timeout 3m
  only:
    - master
    
sentry/deploy:
  stage: post-deploy
  image: getsentry/sentry-cli
  variables:
    GIT_STRATEGY: none
  script:
    - sentry-cli releases deploys $VERSION new -e production
    - sentry-cli releases finalize $VERSION
  only:
    - master